//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCompleto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User{

        [Display(Name = "ID:")]
        public int id { get; set; }

        [Display(Name = "Login:")]
        [Required(ErrorMessage = "Informe o nome de usuário", AllowEmptyStrings = false)]
        public string username { get; set; }

        [Display(Name = "Senha:")]
        [Required(ErrorMessage = "Informe o senha do usuário", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string password { get; set; }

    }
}
